name: test outputs var

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      update_dl_cache_needed: ${{ steps.update-dl-cache.outputs.needed }}
    steps:
      - name: set output
        id: update-dl-cache
        run: |
          # echo "needed=true" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: retrieve output
        run: |
          echo ${{ needs.job1.outputs.update_dl_cache_needed }}


  job2_if_true:
    runs-on: ubuntu-latest
    if: ${{ needs.job1.outputs.update_dl_cache_needed == 'true' }}    
    needs: job1
    steps:
      - name: retrieve output
        run: |
          echo ${{ needs.job1.outputs.update_dl_cache_needed }}
