name: Firmware build and upload

on: push

env:
  CACHE_DIR: ${{ github.workspace }}/.cache

jobs:
  firmware-build:
    runs-on: ubuntu-latest
    outputs:
      update-dl-cache-needed: ${{ steps.update-dl-cache.outputs.needed }}
    strategy:
      matrix:
        product: [unified, waffle]
        type: [internal, release]
    env:
      typ_product: ${{ matrix.product }}-${{ matrix.type }}
    steps:
      - name: Compute cache download size
        id: dl-cache-size
        run: |
          mkdir -p "${CACHE_DIR}/dl"
          CURRENT=$(du -sb "${CACHE_DIR}/dl" | cut -f1)
          echo "current=$CURRENT" >> "$GITHUB_OUTPUT"

      - name: Build OS
        run: |
          LEN=$(( RANDOM % (MAX-MIN+1) + MIN ))
          echo "$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$LEN")" > "${CACHE_DIR}/dl/a"
          sleep 180

      - name: Check cache download needs to be updated
        id: update-dl-cache
        run: |
          CURRENT=$(du -sb "${CACHE_DIR}/dl" | cut -f1)
          echo "Cache size before:${{ steps.dl-cache-size.outputs.current }} after:$CURRENT"
          if [[ "${{ steps.dl-cache-size.outputs.current }}" -ne "$CURRENT" ]]; then
            echo "needed=true" | tee -a "$GITHUB_OUTPUT"
          fi

  update-dl-cache:
    needs: firmware-build
    runs-on: ubuntu-latest
    if: ${{ needs.firmware-build.outputs.update-dl-cache-needed == 'true' }}
    steps:

      - name: Dump out
        run: |
          echo "$GITHUB_OUTPUT"
        timeout-minutes: 120