name: test outputs var

on: push

jobs:
  firmware-build:
    runs-on: ubuntu-latest
    outputs:
      update-dl-cache-needed: ${{ steps.update-dl-cache.outputs.needed }}
    strategy:
      matrix:
        product: [unified, waffle]
        type: [internal, release]
    env:
      typ_product: ${{ matrix.product }}-${{ matrix.type }}
    steps:
      - name: Check cache download needs to be updated
        id: update-dl-cache
        run: |
          echo "needed=true" >> "$GITHUB_OUTPUT"
          
  update-dl-cache:
    needs: firmware-build
    runs-on: ubuntu-latest
    if: ${{ needs.firmware-build.outputs.update-dl-cache-needed == 'true' }}
    steps:

      - name: Dump out
        run: |
          echo "$GITHUB_OUTPUT"
        timeout-minutes: 120